name: K9s Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run Tests
        run: make test
        env:
          CGO_ENABLED: '0'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.24.2

      - name: Publish Release
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
